### ISSUE TITLE
(Possibly) Utilize magic to relieve some of the runtime unary natural cost

### ISSUE THREAD

**Issue by jake-87** [mikeshulman/narya#10]
It's noted at the bottom of the README that there are some minor concerns around unary natural performance - if these become an issue, many of the functions in `util/n.ml` can be replaced (or supplemented) with equivalent (but internally less type safe) versions. For example:
```ocaml
let rec plus : type m n. n t -> (m, n) has_plus = function
  | Nat Zero -> Plus Zero
  | Nat (Suc n) ->
      let (Plus mn) = plus (Nat n) in
      Plus (Suc mn)
```
is equivalent to
```ocaml
let plus_magic : type a b c d e f. (a, b, c) plus ->  (d, e, f) plus = Obj.magic 

let plus' : type m n. n t -> (m, n) has_plus =
  fun n ->
    let (Nat n) = n in
    Plus (plus_magic n)
```
It's obvious that this function itself is still runtime-safe, as we're only `magic`ing phantom GADT parameters, but via some visual (or automatic) analysis, it's clear that this is semantically equivalent as well, while running in constant time.

This may not be needed at any point, but if a performance issue is raised, it may help. 

Just as an already-noted con, this does set some sort of precedent around "cheating" the type safety of the typechecker and surrounding.

**Comment by mikeshulman** [comment]
Yes, I had similar thoughts as well.  My thought was that it should be possible to swap out `n.ml` for something like
```ocaml
type (_, _, _) plus = Fake : int -> (unit, unit, unit) plus (* the value of 'b *)
```
(the value of `b` being the one that gets computed with at runtime).  Then we would keep some other types like
```ocaml
type _ t = Nat : ('any, 'n, 'anyn) plus -> 'n t

type (_, _) has_plus = Plus : ('m, 'n, 'mn) plus -> ('m, 'n) has_plus
```
but the operations would just turn into ordinary integer ones:
```ocaml
let plus : type m n. n t -> (m, n) has_plus = fun (Nat n) -> Plus (Fake n)

let rec plus_out : type m n mn. m t -> (m, n, mn) plus -> mn t =
  fun (Fake m) (Fake n) -> Nat (Fake (m + n))

let plus_left : type m n mn. (m, n, mn) plus -> mn t -> m t =
  fun (Fake n) (Nat (Fake mn)) -> Nat (Fake (mn - n))

let plus_uniq : type m n mn mn'. (m, n, mn) plus -> (m, n, mn') plus -> (mn, mn') Eq.t =
  fun _ _ -> Eq
```
I don't completely understand `Obj.magic`, but my guess is that it would only work for operations like `plus` that are a no-op on the underlying computational integer, whereas using machine integers would also speed up operations like `plus_out` and `plus_left` that actually do arithmetic.

Ideally, an efficient implementation like this could be swapped in and out with the type-safe one: ensuring that the code continues to work with the type-safe implementation would maintain the same guarantees of correctness, while it could be compiled with the efficient version for real-world use.  One way to make this happen this would be with [virtual libraries](https://dune.readthedocs.io/en/stable/variants.html).  When I first learned about virtual libraries I was unhappy that they prevent the code from being loaded in `utop`, but now that the executable is fairly robust I don't use `utop` much any more, so I might consider that.

This is all for the future, of course.  I am trying to be adamant about avoiding premature optimization, and at present unary natural number arithmetic does not seem to be a bottleneck.

**Comment by mikeshulman** [comment]
> at present unary natural number arithmetic does not seem to be a bottleneck.

More precisely, I should say that I don't *yet* have evidence that is *is* a bottleneck.  As noted at #9, it's difficult to figure out where the bottlenecks are since OCaml 5 doesn't have good memory profiling tools yet, and I haven't put a lot of effort into it because my focus is on getting the code correct before worrying too much about making it fast.

**Comment by jake-87** [comment]
Reasonable concerns, on both points - I would assume that performance concerns would only come to pass when indices get into the thousands or higher.

As for a full transition to machine integers, I don't see why your proposed interface wouldn't work; you're also correct in saying that an `Obj.magic` solution wouldn't solve the cases where actual computation (that isn't simply reconstructing the same object with a different type, or similar) is being performed. 

My suggestion was simply a "here's an easy thing you could do to save time in a (probably) somewhat common case". Without profiling I assume it's hard to tell, however, so take that with a grain of salt 😅  

I'll probably close this issue for the moment, seeing as performance issues aren't on the horizon yet.

ps.
`Obj.magic` is, from digging into the source of the `Obj` library in the stdlib, essential an identity function with type `'a -> 'b`; i.e, it's a deliberate hole in the type system. This of course makes it very easy to violate invariants with, but it also means that in controlled situations like the above, you can skip out on computation that's only done for the sake of type agreement.

**Comment by mikeshulman** [comment]
Thanks for the suggestion, and for the kind words!  I'll keep `Obj.magic` in mind.
