### ISSUE TITLE
Matching doesn't seem to eliminate

### ISSUE THREAD

**Issue by olynch** [mikeshulman/narya#28]
I'm trying to prove that the naturals are discrete, and I'm confused about the behavior of `match`. Specifically, I have the following:

```
def NatIsDisc : IsDisc ℕ := (
  trunc_id := [
  | zero., zero. ↦ (
    trunc_id := f g ↦ match f, g [
    | zero., zero. ↦ ?
    | suc. n, zero. ↦ ?
    | zero., suc. m ↦ ?
    | suc. n, suc. m ↦ ?
    ]
  )
  | zero., (suc. m) ↦ ?
  | (suc. n), zero. ↦ ?
  | (suc. n), (suc. m) ↦ ?
  ],
)
```

The first hole shows up as:

```
H0 ≔ 0 : ℕ (not in scope)
H ≔ 0 : ℕ (not in scope)
f : refl ℕ 0 0
g : refl ℕ 0 0
----------------------------------------------------------------------
IsTrunc minustwo. (ℕ⁽ᵉᵉ⁾ 0 0 0 0 0 0 f g)
```

Why don't I have `f := zero.` and `g := zero.`?

**Comment by mikeshulman** [comment]
The type of `f` and `g` is not fully general over its indices, so matching doesn't refine the goal.  That is, `Id ℕ 0 0` is not inductively generated by `refl zero.` -- only the family of `Id ℕ x y` for all `x` and `y` together is inductively generated by `refl zero.` and `refl suc.`.

**Comment by mikeshulman** [comment]
I think there should be a warning issued when this happens.

**Comment by olynch** [comment]
Ah, OK! I guess that would explain the error message I'm getting when I try to do this another way:

`   ^ match will not refine the goal or context (index is not a free variable): 0`

How would you prove this then?

**Comment by mikeshulman** [comment]
Well, I don't really know what you're trying to prove, as you didn't include all of your code.  Narya's `Id` type isn't fibrant yet, so there's a lot of HoTT that you can't do with it.

**Comment by olynch** [comment]
I'm trying to prove that the naturals are discrete, using 

```
def trunc_index : Type ≔ data [ minustwo. | suc. (_ : trunc_index) ]

def IsTrunc (n:trunc_index) (A:Type) : Type ≔ match n [
| minustwo. ↦ sig ( center : A, contr : (x:A) → Id A center x )
| suc. n ↦ sig ( trunc_id : (x y : A) → IsTrunc n (Id A x y) )
]
```

Also, is this something that could be more ergonomic if narya had unification? E.g., matching over `Id ℕ 0 0` would only need to cover the `zero.` case, because narya can infer that no other constructor is applicable? My feeling from using other proof assistants is that this happens, but perhaps I'm misremembering.

**Comment by mikeshulman** [comment]
Thanks.  Normally in HoTT we call that property "being a set", at least when Id is fibrant; "discrete" has other connotations and is usually best avoided for this.

I don't think you'll be able to prove this without fibrancy of Id.  The standard proof is in the HoTT Book, Theorem 2.13.1, but it uses fibrancy.

Proof assistants vary in the sort of additional refinement they're willing to do.  Agda in particular has a powerful pattern-matching engine that uses a simple sort of unification to eliminate impossible cases based on values of indices.  (Indeed, its original version is *too* powerful, hence the need for `--without-K`.)  I haven't ruled out something of this sort for Narya in the future, but up until now I haven't touched anything needing any kind of unification.

**Comment by olynch** [comment]
OK, I don't think I fully appreciated how little you could do without fibrancy! This is a good learning experience.
